# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import api
import urllib3
from api import api_client, configuration, schemas
from api.paths.tombstone_seed import get  # noqa: E501

from .. import ApiTestMixin


class TestTombstoneSeed(ApiTestMixin, unittest.TestCase):
    """
    TombstoneSeed unit test stubs
        Get the tombstones for the given seed  # noqa: E501
    """

    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200


if __name__ == "__main__":
    unittest.main()
