# coding: utf-8

"""
    Survive the Dungeon API

    API for the online features of Survive the Dungeon game.  Play the game here: https://replit.com/@mattiselin/Survive-the-Dungeon?v=1  The game does not depend on online play at all, but this API offers some socialfeatures that would otherwise not be present.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from api.paths.daily_.get import GetDailyRoute


class DailyApi(
    GetDailyRoute,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
