name: Build Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip virtualenv
        python -m virtualenv venv
        .\venv\Scripts\activate
        python -m pip install -r requirements.txt
        python -m poetry install
    - name: Build Windows executable
      run: |
        .\venv\Scripts\activate
        .\build.bat
    - name: Upload EXE
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/survive.exe
        asset_name: survive.exe
        asset_content_type: application/vnd.microsoft.portable-executable
