name: Create Release

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m poetry install
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed -n survive \
          --add-data 'ui;ui' \
          --add-data 'fonts/*.ttf;fonts' \
          --add-data 'tiles/*.png;tiles' \
          --add-data 'themes;themes' \
          --add-data 'words;words' \
          -i survive.ico .\survive\main.py
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ github.event.head_commit.message }}
        overwrite: true
    - name: Upload EXE
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/survive.exe
        asset_name: survive.exe
        asset_content_type: application/vnd.microsoft.portable-executable
